version: '3.4'

services:
  athelo-backend-api:
    restart: always
    image: athelo-backend
    volumes: 
      - ./rest-api:/app
      - ./application_default_credentials.json:/application_default_credentials.json
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:8000
    environment:
    - ENVIRONMENT=local
    - GOOGLE_APPLICATION_CREDENTIALS=/application_default_credentials.json
    - GOOGLE_CLOUD_PROJECT=test-deploy-402816
    stdin_open: true
    tty: true 
    # command: tail -f /dev/null
    command: python3 app.py
    depends_on:
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=athelo
      - POSTGRES_PASSWORD=athelo
      - POSTGRES_DB=athelo
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redispassword

volumes:
  postgres_data:
  redis_data:
