version: '3.4'

services:
  athelo-backend-api:
    restart: always
    image: athelo-backend
    volumes: 
      - ./rest-api:/app
      - ./application_default_credentials.json:/application_default_credentials.json
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:8080
    environment:
    - ENVIRONMENT=local
    - GOOGLE_APPLICATION_CREDENTIALS=/application_default_credentials.json
    - GOOGLE_CLOUD_PROJECT=test-deploy-402816
    stdin_open: true
    tty: true 
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=athelo
      - POSTGRES_PASSWORD=athelo
      - POSTGRES_DB=athelo

volumes:
  postgres_data: