version: '3.4'

services:
  athelo-backend-api:
    restart: always
    image: athelo-backend
    volumes: 
      - ./athelo:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5000
    environment:
    - ENVIRONMENT=local
    stdin_open: true
    tty: true 
    command: flask --debug run --host=0.0.0.0 --port=5000
    # command: tail -f /dev/null
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=athelo
      - POSTGRES_PASSWORD=athelo
      - POSTGRES_DB=athelo

volumes:
  postgres_data: