"""switch from non-alembic defaults

Revision ID: c6397f0cef4d
Revises: 2615d8e15365
Create Date: 2024-01-07 17:19:45.372174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6397f0cef4d'
down_revision = '2615d8e15365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_channels', schema=None) as batch_op:
        batch_op.alter_column('users_hash',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_channels', schema=None) as batch_op:
        batch_op.alter_column('users_hash',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
