"""add image url to user

Revision ID: 3f4d00fc4b04
Revises: 58f449cb9fdf
Create Date: 2024-02-07 15:48:43.753345

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3f4d00fc4b04"
down_revision = "58f449cb9fdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###
