"""add vonage support

Revision ID: 52c8e1552517
Revises: 76a9a21b593d
Create Date: 2024-01-30 16:16:11.451915

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "52c8e1552517"
down_revision = "76a9a21b593d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vonage_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_vonage_sessions_appointment_id_appointments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vonage_sessions")),
    )
    op.create_table(
        "zoom_meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("zoom_host_url", sa.String(), nullable=True),
        sa.Column("zoom_join_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_zoom_meetings_appointment_id_appointments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zoom_meetings")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zoom_meetings")
    op.drop_table("vonage_sessions")
    # ### end Alembic commands ###
