"""convert saved content UUID to string

Revision ID: 58f449cb9fdf
Revises: 854223b6d108
Create Date: 2024-02-02 22:34:08.295451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58f449cb9fdf'
down_revision = '854223b6d108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_content', schema=None) as batch_op:
        batch_op.alter_column('external_content_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_content', schema=None) as batch_op:
        batch_op.alter_column('external_content_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='external_content_id::uuid')
    # ### end Alembic commands ###
