"""update provider and appointment for zoom

Revision ID: 76a9a21b593d
Revises: d28ce4eb5700
Create Date: 2024-01-29 05:02:33.391112

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "76a9a21b593d"
down_revision = "d28ce4eb5700"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("zoom_host_url", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("zoom_join_url", sa.String(), nullable=True))
        batch_op.drop_column("zoom_token")
        batch_op.drop_column("zoom_url")

    with op.batch_alter_table("provider_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("zoom_user_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("zoom_refresh_token", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_profiles", schema=None) as batch_op:
        batch_op.drop_column("zoom_refresh_token")
        batch_op.drop_column("zoom_user_id")

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("zoom_url", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("zoom_token", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("zoom_join_url")
        batch_op.drop_column("zoom_host_url")

    # ### end Alembic commands ###
