"""add provider type

Revision ID: 854223b6d108
Revises: 52c8e1552517
Create Date: 2024-02-01 15:13:33.788489

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "854223b6d108"
down_revision = "52c8e1552517"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    provider_type = postgresql.ENUM("CARE_NAVIGATOR", name="providertype")
    provider_type.create(op.get_bind())

    with op.batch_alter_table("provider_profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "provider_type",
                sa.Enum("CARE_NAVIGATOR", name="providertype"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_profiles", schema=None) as batch_op:
        batch_op.drop_column("provider_type")

    provider_type = sa.Enum(
        "CARE_NAVIGATOR",
        name="providertype",
        metadata=sa.MetaData(),
    )

    provider_type.drop(bind=op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
