"""empty message

Revision ID: b7158698cb1c
Revises: ebaf5e58f37a
Create Date: 2024-01-13 16:38:42.804766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7158698cb1c'
down_revision = 'ebaf5e58f37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=False))
        batch_op.alter_column('birthday',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('test')

    # ### end Alembic commands ###
