"""switch from non-alembic defaults

Revision ID: c6397f0cef4d
Revises: 2615d8e15365
Create Date: 2024-01-07 17:19:45.372174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6397f0cef4d'
down_revision = '2615d8e15365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_channel_members_message_channel_id_message_channels'), 'message_channels', ['message_channel_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_channel_members_user_profile_id_profiles'), 'profiles', ['user_profile_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_messages_channel_id_message_channels'), 'message_channels', ['channel_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_author_id_profiles'), 'profiles', ['author_id'], ['id'])

    with op.batch_alter_table('saved_content', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_saved_content_user_profile_id_profiles'), 'profiles', ['user_profile_id'], ['id'])

    with op.batch_alter_table('user_symptoms', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_symptoms_user_profile_id_profiles'), 'profiles', ['user_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_symptoms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_symptoms_user_profile_id_profiles'), type_='foreignkey')

    with op.batch_alter_table('saved_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_saved_content_user_profile_id_profiles'), type_='foreignkey')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_author_id_profiles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_channel_id_message_channels'), type_='foreignkey')

    with op.batch_alter_table('channel_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_channel_members_user_profile_id_profiles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_channel_members_message_channel_id_message_channels'), type_='foreignkey')

    op.create_table('votes',
    sa.Column('vote_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_cast', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('candidate', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('vote_id', name='votes_pkey')
    )
    # ### end Alembic commands ###
